### ISSUE TITLE
Error when search type is playlist

### ISSUE THREAD

**Issue by AayushGour** [DevAndromeda/youtube-sr#44]
When I try to search with a particular word and the type is set to "playlist" then I'm facing the following Issue.

`TypeError: this.thumbnail.toJSON is not a function at Playlist.toJSON (node_modules\youtube-sr\dist\mod.js:266:33)`

Here is my Code...

`let searchData = await YouTube.search(searchParam, { limit: 10, type: "playlist" })`

**Comment by DevAndromeda** [comment]
https://github.com/DevAndromeda/youtube-sr/commit/79e0dd15d02024ca530c86bb98d8ffd63cf5882f should fix the issue related to `TypeError: this.thumbnail.toJSON is not a function at Playlist.toJSON (node_modules\youtube-sr\dist\mod.js:266:33)`
